### ISSUE TITLE
Domain Adaptation

### ISSUE THREAD

**Issue by Zhou-Hangyu** [JiwanChung/esper#2]
Awesome work! Just a quick question. When adapting ESPER to some specific domains like news image captioning, do you need to update the encoder in any way? Or do you keep that frozen and only train & finetune the LM?

**Comment by JiwanChung** [comment]
Sadly we did not experiment with task transfer learning. Still, based on the COCO-caption fine-tuning results we shared on the paper, I presume that training LM only would work reasonably well.

Just in case I misunderstood your intention, let me remind that ESPER suggests training with RL for all the required domains. RL is costly, though. So I hope your suggested direction opens yet another use case of our work :)

**Comment by Zhou-Hangyu** [comment]
Thank you for the timely response! I'm actually referring to Section 2.3 (Adaptation on Pretrained Language Model). My confusion arises from the intuition that the encoder is LM-dependent. So, if you fine-tune the LM, it seems logical that you'd also need to update the encoder's parameters. However, the paper only mentions using RL to fine-tune the backbone without any paired data, (which is impressive, CLIP is awesome). Am I overlooking something, or is the encoder actually kept frozen during this adaptation, contrary to my intuition?

**Comment by JiwanChung** [comment]
During the RL stage, we freeze the LM parameters and train only the lightweight encoder between the extracted CLIP image features and the LM. In section 2.3, we described fine-tuning LM with text-only data prior to applying multimodal RL.

It might seem counter-intuitive that our light encoder (one-or-two layers of MLP) is expressive enough for multimodal adaptation. However, it is a common practice in image captioning literature (CLIPCap: https://arxiv.org/abs/2111.09734, LLAVA-stage-1: https://llava-vl.github.io/) which is known to work well. I attribute this to the expressiveness of the LM and the linear probing capability of CLIP being strong enough for such tasks.

Still, one may also de-freeze the LM while training with ESPER. We could not look into that direction because of the computational resource limits, but it can lead to performance improvements depending on the hyperparameter setups.

**Comment by Zhou-Hangyu** [comment]
Thank you! That makes a lot more sense. So, for each domain (e.g., News, Dialog), you first fine-tuned GPT-2 on that domain-specific text data, then froze it, and trained the lightweight encoder using RL. Do these domain-specific ESPERs (ESPER-Domain) share the same lightweight encoder checkpoint, or do you have to train a new one from scratch for each domain-specific ESPER?

**Comment by JiwanChung** [comment]
You can train it either way. We used the former method (sharing LM and lightweight encoder for multi-tasking) to reduce the number of RL training processes (which take days). Personally, I recommend you use a multitask setup with standard image captioning + a few other domain-specific tasks for efficiency and to prevent distribution collapse during RL updates.

**Comment by Zhou-Hangyu** [comment]
Got it, thank you!
