### ISSUE TITLE
Something problems related to experimental models

### ISSUE THREAD

**Issue by WangYao-GoGoGo** [JiwanChung/esper#3]
Hello, I felt your paper is very interesting after I read. Since my direction is not in this domain, so I have some questions about your experimental models.

①、what is the difference between **ESPER-MLP** and **ESPER-FULL** in model structure
②、In addition to some clues like "news", what is the difference between ESPER-Style model and other models (SPER-MLP and ESPER-FULL)？

I'm looking forward to hearing your reply!
Thank you very much !

**Comment by JiwanChung** [comment]
Thank you for noticing our paper!

1. ESPER-MLP and ESPER-FULL concerns transfer learning problems, in which we transfer MLP weights trained with ESPER to the supervised learning stage. In that case, we can either train only the MLP weights (since that's what we trained before in ESPER) or train both the MLP and the LM weights (hence, FULL). Architecture-wise, they are exactly the same except for the part of the model that is trained in the supervised stage.
2. ESPER-Style should be compared with ESPER-Free. ESPER-Style is trained on top of the text-only language model fine-tuned on domain-specific text-only data, while ESPER-free is trained on top of a general-purpose language model such as vanilla GPT2. ESPER-MLP and ESPER-FULL are terms from the transfer learning setup only.

**Comment by WangYao-GoGoGo** [comment]
Thank you very much for your detailed description.
